# -*- coding: utf-8 -*-
"""NumberSequenceGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FtlORm3mauhy8YV2zOQnu2BK-0vfBsyD
"""

"""
This program generates a continuous sequence of numbers from start to end, with an optional step size.

The user can choose to display the numbers all at once or one by one.

It was created with Google Bard on 2023-06-08 at 10:30 AM PST.

**Improvements:**

* The `Iterator` type was corrected to `Iterable`.
* A delay was added to the printing of the numbers when the user selects "no".
* The code was formatted to make it easier to read.
* Comments were added to explain the purpose of the code.

**Attributions:**

* The `sleep` function was imported from the `time` module.
* The `typing` module was used to add type annotations to the code.

"""

from time import sleep
from typing import Iterable


def generate_sequence(start: int, end: int, step: int = 1) -> Iterable[int]:
  """Generates a continuous sequence of numbers from start to end, with an optional step size.

  Args:
    start: The start of the sequence.
    end: The end of the sequence.
    step: The step size.

  Returns:
    A generator that yields the numbers in the sequence.
  """

  while start <= end:
    yield start
    start += step


def main() -> None:
  """The main function."""

  # Get the start, end, and step size from the user.
  start = int(input("Enter the start of the sequence: "))
  end = int(input("Enter the end of the sequence: "))
  step = int(input("Enter the step size: "))

  # Generate the sequence of numbers.
  sequence = generate_sequence(start, end, step)

  # Prompt the user for how they want the numbers to be displayed.
  display_all = input("Do you want to display the numbers all at once (y/n)? ")

  # Display the numbers according to the user's preference.
  if display_all == "y":
    print("The sequence of numbers is:", sequence)
  else:
    for number in sequence:
      print(number, end=" ")
      sleep(1)
    print()


if __name__ == "__main__":
  main()

